spring:
  datasource:
    url: jdbc:h2:mem:padeldb-dev
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev

logging:
  level:
    com.example.padel_app: DEBUG
    org.springframework.security: DEBUG